//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axh.Wedding.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axh.Wedding.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string ContactPage_Link {
            get {
                return ResourceManager.GetString("ContactPage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have questions? We have answers (maybe).
        /// </summary>
        public static string ContactPage_SubTitle {
            get {
                return ResourceManager.GetString("ContactPage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactPage_Title {
            get {
                return ResourceManager.GetString("ContactPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Wedding.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string InformationPage_Link {
            get {
                return ResourceManager.GetString("InformationPage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps, hotels and stuff.
        /// </summary>
        public static string InformationPage_SubTitle {
            get {
                return ResourceManager.GetString("InformationPage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationPage_Title {
            get {
                return ResourceManager.GetString("InformationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSVP.
        /// </summary>
        public static string RsvpPage_Link {
            get {
                return ResourceManager.GetString("RsvpPage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope to see you there.
        /// </summary>
        public static string RsvpPage_SubTitle {
            get {
                return ResourceManager.GetString("RsvpPage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If It Pleases You.
        /// </summary>
        public static string RsvpPage_Title {
            get {
                return ResourceManager.GetString("RsvpPage_Title", resourceCulture);
            }
        }
    }
}
