//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axh.Wedding.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axh.Wedding.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password.
        /// </summary>
        public static string Account_InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("Account_InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Account_SignIn {
            get {
                return ResourceManager.GetString("Account_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Account_SignOut {
            get {
                return ResourceManager.GetString("Account_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string AdminPage_Actions {
            get {
                return ResourceManager.GetString("AdminPage_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AdminPage_Delete {
            get {
                return ResourceManager.GetString("AdminPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AdminPage_Edit {
            get {
                return ResourceManager.GetString("AdminPage_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string AdminPage_Link {
            get {
                return ResourceManager.GetString("AdminPage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string AdminPage_Title {
            get {
                return ResourceManager.GetString("AdminPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Man.
        /// </summary>
        public static string BestMan {
            get {
                return ResourceManager.GetString("BestMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactPage_Link {
            get {
                return ResourceManager.GetString("ContactPage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have questions? We have answers (maybe).
        /// </summary>
        public static string ContactPage_SubTitle {
            get {
                return ResourceManager.GetString("ContactPage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactPage_Title {
            get {
                return ResourceManager.GetString("ContactPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dad.
        /// </summary>
        public static string Dad {
            get {
                return ResourceManager.GetString("Dad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dietary Requirements.
        /// </summary>
        public static string DietaryRequirements {
            get {
                return ResourceManager.GetString("DietaryRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Type.
        /// </summary>
        public static string GuestType {
            get {
                return ResourceManager.GetString("GuestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding.
        /// </summary>
        public static string HomePage_Link {
            get {
                return ResourceManager.GetString("HomePage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Wedding.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting there.
        /// </summary>
        public static string InformationPage_GettingThere {
            get {
                return ResourceManager.GetString("InformationPage_GettingThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something to Buy.
        /// </summary>
        public static string InformationPage_Gifts_Title {
            get {
                return ResourceManager.GetString("InformationPage_Gifts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date has been set and we’d love you to come,&lt;br /&gt;
        ///To celebrate our wedding, a long way for some,&lt;br /&gt;
        ///All you must do, is decide what to wear,&lt;br /&gt;
        ///Then polish your jewellery and comb up your hair..
        /// </summary>
        public static string InformationPage_Honeymoon_Poem_1 {
            get {
                return ResourceManager.GetString("InformationPage_Honeymoon_Poem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t worry about gifts, don’t buy us a yacht,&lt;br /&gt;
        ///The things that we need, we’ve already got.&lt;br /&gt;
        ///Our home is quite compact, we may have to move&lt;br /&gt;
        ///Then our storage and space will surely improve..
        /// </summary>
        public static string InformationPage_Honeymoon_Poem_2 {
            get {
                return ResourceManager.GetString("InformationPage_Honeymoon_Poem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t go out shopping or get yourself stressed,&lt;br /&gt;
        ///Don’t alter your plans for a pre wedding rest.&lt;br /&gt;
        ///If you want to be generous, despite what we’ve said,&lt;br /&gt;
        ///Then save all the hassle and do this instead....
        /// </summary>
        public static string InformationPage_Honeymoon_Poem_3 {
            get {
                return ResourceManager.GetString("InformationPage_Honeymoon_Poem_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t know how to word this but will give it our best shot…&lt;br /&gt;
        ///Contributions are most welcome, we’ll go somewhere hot!&lt;br /&gt;
        ///A honeymoon would be marvellous, to start off our life.&lt;br /&gt;
        ///In our long winding journey, as new husband and wife!.
        /// </summary>
        public static string InformationPage_Honeymoon_Poem_4 {
            get {
                return ResourceManager.GetString("InformationPage_Honeymoon_Poem_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closest hotel is Dakota Nottingham, a ten minute drive from Goosedale..
        /// </summary>
        public static string InformationPage_Hotels_1 {
            get {
                return ResourceManager.GetString("InformationPage_Hotels_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manager has kindly arranged a special discounted room rate for any of our guests that would like to stay at the hotel. A double room is £79 including breakfast and a single is £70 including breakfast. To guarantee a room, call quoting &lt;span class=&quot;subtle&quot;&gt;&apos;Kathryn &amp; Alex, Goosedale Wedding 14th March 2015&apos;&lt;/span&gt;..
        /// </summary>
        public static string InformationPage_Hotels_2 {
            get {
                return ResourceManager.GetString("InformationPage_Hotels_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will be staying there and we couldn&apos;t wish for a better ending to our wedding than to share our first breakfast as husband and wife (as in proper bacon and eggs breakfast) with our closest friends and family..
        /// </summary>
        public static string InformationPage_Hotels_3 {
            get {
                return ResourceManager.GetString("InformationPage_Hotels_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhere to Stay.
        /// </summary>
        public static string InformationPage_Hotels_Title {
            get {
                return ResourceManager.GetString("InformationPage_Hotels_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be exchanging their wedding vows.
        /// </summary>
        public static string InformationPage_Introduction_1 {
            get {
                return ResourceManager.GetString("InformationPage_Introduction_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please join us to celebrate our special day from 12:30 PM..
        /// </summary>
        public static string InformationPage_Introduction_Day {
            get {
                return ResourceManager.GetString("InformationPage_Introduction_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please join us for drinks, dancing and live music at our evening reception from 7:00 PM..
        /// </summary>
        public static string InformationPage_Introduction_Evening {
            get {
                return ResourceManager.GetString("InformationPage_Introduction_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InformationPage_Link {
            get {
                return ResourceManager.GetString("InformationPage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stuff we couldn&apos;t fit on the invitation.
        /// </summary>
        public static string InformationPage_SubTitle {
            get {
                return ResourceManager.GetString("InformationPage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationPage_Title {
            get {
                return ResourceManager.GetString("InformationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s right, we changed the venue....
        /// </summary>
        public static string InformationPage_Venue_1 {
            get {
                return ResourceManager.GetString("InformationPage_Venue_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPage_Link {
            get {
                return ResourceManager.GetString("LoginPage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you?.
        /// </summary>
        public static string LoginPage_SubTitle {
            get {
                return ResourceManager.GetString("LoginPage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello..
        /// </summary>
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mum.
        /// </summary>
        public static string Mum {
            get {
                return ResourceManager.GetString("Mum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some jarb about.
        /// </summary>
        public static string RandomStoryTitleLabels_0 {
            get {
                return ResourceManager.GetString("RandomStoryTitleLabels_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the scoop on.
        /// </summary>
        public static string RandomStoryTitleLabels_1 {
            get {
                return ResourceManager.GetString("RandomStoryTitleLabels_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confessions about.
        /// </summary>
        public static string RandomStoryTitleLabels_2 {
            get {
                return ResourceManager.GetString("RandomStoryTitleLabels_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than we need to know about.
        /// </summary>
        public static string RandomStoryTitleLabels_3 {
            get {
                return ResourceManager.GetString("RandomStoryTitleLabels_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pure filth on.
        /// </summary>
        public static string RandomStoryTitleLabels_4 {
            get {
                return ResourceManager.GetString("RandomStoryTitleLabels_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets from the front line on.
        /// </summary>
        public static string RandomStoryTitleLabels_5 {
            get {
                return ResourceManager.GetString("RandomStoryTitleLabels_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday 14th March 2015.
        /// </summary>
        public static string Rsvp_Date_Long {
            get {
                return ResourceManager.GetString("Rsvp_Date_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Saturday, the fourteenth of March two thousand fifteen.
        /// </summary>
        public static string Rsvp_Date_Wordy {
            get {
                return ResourceManager.GetString("Rsvp_Date_Wordy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If we&apos;ve missed anyone off please add them..
        /// </summary>
        public static string Rsvp_PleaseAddMissingGuests {
            get {
                return ResourceManager.GetString("Rsvp_PleaseAddMissingGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you’ve got 2 minutes and some interesting or funny stories about anyone in the wedding party then we’d love for you to sign our guestbook. Why not eh?.
        /// </summary>
        public static string Rsvp_PleaseAddStory {
            get {
                return ResourceManager.GetString("Rsvp_PleaseAddStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check details for all wedding guests in your party. If we&apos;ve made any mistakes then please correct them..
        /// </summary>
        public static string Rsvp_PleaseRsvp {
            get {
                return ResourceManager.GetString("Rsvp_PleaseRsvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at one o&apos;clock in the afternoon.
        /// </summary>
        public static string Rsvp_Time_Wordy {
            get {
                return ResourceManager.GetString("Rsvp_Time_Wordy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goosedale.
        /// </summary>
        public static string Rsvp_Venue {
            get {
                return ResourceManager.GetString("Rsvp_Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papplewick.
        /// </summary>
        public static string Rsvp_Venue_Location {
            get {
                return ResourceManager.GetString("Rsvp_Venue_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You missed someone off....
        /// </summary>
        public static string RsvpPage_AddGuest {
            get {
                return ResourceManager.GetString("RsvpPage_AddGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add story or interesting fact....
        /// </summary>
        public static string RsvpPage_AddStory {
            get {
                return ResourceManager.GetString("RsvpPage_AddStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received your RSVP on.
        /// </summary>
        public static string RsvpPage_Alert_Success {
            get {
                return ResourceManager.GetString("RsvpPage_Alert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any dietary requirements?.
        /// </summary>
        public static string RsvpPage_DietaryRequirements {
            get {
                return ResourceManager.GetString("RsvpPage_DietaryRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rsvp.
        /// </summary>
        public static string RsvpPage_Link {
            get {
                return ResourceManager.GetString("RsvpPage_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t wait to share our special day with you.
        /// </summary>
        public static string RsvpPage_SubTitle {
            get {
                return ResourceManager.GetString("RsvpPage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come Celebrate.
        /// </summary>
        public static string RsvpPage_Title {
            get {
                return ResourceManager.GetString("RsvpPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string RsvpResponse {
            get {
                return ResourceManager.GetString("RsvpResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry can&apos;t make it :-(.
        /// </summary>
        public static string RsvpResponse_No {
            get {
                return ResourceManager.GetString("RsvpResponse_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yep, I&apos;m coming, can&apos;t wait!.
        /// </summary>
        public static string RsvpResponse_Yes {
            get {
                return ResourceManager.GetString("RsvpResponse_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string User_IsAdmin {
            get {
                return ResourceManager.GetString("User_IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rsvp.
        /// </summary>
        public static string User_RsvpDate {
            get {
                return ResourceManager.GetString("User_RsvpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rsvp Type.
        /// </summary>
        public static string User_RsvpType {
            get {
                return ResourceManager.GetString("User_RsvpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string User_RsvpType_Day {
            get {
                return ResourceManager.GetString("User_RsvpType_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string User_RsvpType_Evening {
            get {
                return ResourceManager.GetString("User_RsvpType_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string User_RsvpType_None {
            get {
                return ResourceManager.GetString("User_RsvpType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will.
        /// </summary>
        public static string WeddingPartyMember_BestMan {
            get {
                return ResourceManager.GetString("WeddingPartyMember_BestMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kathryn.
        /// </summary>
        public static string WeddingPartyMember_Bride {
            get {
                return ResourceManager.GetString("WeddingPartyMember_Bride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molloy.
        /// </summary>
        public static string WeddingPartyMember_Bride_Surname {
            get {
                return ResourceManager.GetString("WeddingPartyMember_Bride_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bridesmaids.
        /// </summary>
        public static string WeddingPartyMember_Bridesmaids {
            get {
                return ResourceManager.GetString("WeddingPartyMember_Bridesmaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paul.
        /// </summary>
        public static string WeddingPartyMember_FatherOfTheBride {
            get {
                return ResourceManager.GetString("WeddingPartyMember_FatherOfTheBride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ralph.
        /// </summary>
        public static string WeddingPartyMember_FatherOfTheGroom {
            get {
                return ResourceManager.GetString("WeddingPartyMember_FatherOfTheGroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alex.
        /// </summary>
        public static string WeddingPartyMember_Groom {
            get {
                return ResourceManager.GetString("WeddingPartyMember_Groom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haslehurst.
        /// </summary>
        public static string WeddingPartyMember_Groom_Surname {
            get {
                return ResourceManager.GetString("WeddingPartyMember_Groom_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawn.
        /// </summary>
        public static string WeddingPartyMember_MotherOfTheBride {
            get {
                return ResourceManager.GetString("WeddingPartyMember_MotherOfTheBride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheila.
        /// </summary>
        public static string WeddingPartyMember_MotherOfTheGroom {
            get {
                return ResourceManager.GetString("WeddingPartyMember_MotherOfTheGroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ushers.
        /// </summary>
        public static string WeddingPartyMember_Ushers {
            get {
                return ResourceManager.GetString("WeddingPartyMember_Ushers", resourceCulture);
            }
        }
    }
}
